name: lms_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.7.6+52

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.7
  http: ^1.1.0
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.0
  flutter_webview_plugin: ^0.4.0
  extended_nested_scroll_view: ^6.1.2
  font_awesome_flutter: ^10.5.0
  flutter_widget_from_html_core: ^0.15.1
  firebase_core_platform_interface: ^5.1.0
  loading_skeleton_niu: ^0.0.1
  http_auth: ^1.0.3
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  stripe_sdk:
    git: https://github.com/s2nventures/stripe-sdk
  percent_indicator: ^4.2.3
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  razorpay_flutter: ^1.3.0
#  open_document:
#    git: https://github.com/emran92/open_document
  open_document: ^1.0.7
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
  webview_flutter: ^4.2.2
  flutter_facebook_auth: ^7.0.1
  google_sign_in: ^6.1.4
  connection_notifier: ^2.0.1
  flutter_inappwebview: ^6.0.0
#  flutter_inappwebview:
#    git:
#      url: https://github.com/VictorUvarov/flutter_inappwebview
#      ref: ios-16-compile-issue
  vdocipher_flutter: ^2.3.2
  flutter_paystack: ^1.0.7
#  flutter_paystack:
#    git:
#      url: https://github.com/definitelyme/flutter_paystack.git
#      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

#  eko_jitsi:
#    git: https://github.com/emran92/eko_jitsi
#  sn_progress_dialog: ^1.0.8
#  fancy_shimmer_image: ^2.0.3
  fancy_shimmer_image:
    path: fancy-shimmer-image
  flutter_blurhash: ^0.8.2
  purchases_flutter: ^6.29.4
  youtube_player_flutter: ^9.0.1
  flutter_slidable: ^3.0.1
#  pod_player: ^0.2.1
#  pod_player:
#    git:
#      url: https://github.com/GeorgeReda/pod_player.git
#      ref: 79eca311d8a1e6970d43ee04d56a7bbcaf9235ad
  google_fonts: ^6.2.1
  awesome_notifications: ^0.9.3+1
  flutter_windowmanager: ^0.2.0
  video_player: ^2.9.0
  chewie: ^1.8.1
  flick_video_player: ^0.8.0
#  package_info_plus_windows:
#    path: package_info_plus_windows-2.1.0
#  package_info_plus: ^1.4.3+1
#win32: ^5.0.6
  persistent_bottom_nav_bar:
      git:
        url: https://github.com/HamzaSamirAmmar/PersistentBottomNavBar.git

dependency_overrides:
  http: ^0.13.1
  reactive_forms: 10.1.0
  file_picker: ^5.0.1
  file: ^6.1.4
#  package_info_plus: ^1.3.0
  webview_flutter: ^3.0.0
#  pod_player: ^0.1.5

  # freezed_annotation: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf